services:
  db:
    image: postgres:17
    container_name: auth_kairos
    restart: unless-stopped
    environment:
      POSTGRES_DB: kairos-auth
      POSTGRES_USER: kairos-user
      POSTGRES_PASSWORD: kairos-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kairos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kairos-user -d kairos-auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: kairos-auth
      dockerfile: Dockerfile
    container_name: auth_service
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kairos-auth
      SPRING_DATASOURCE_USERNAME: kairos-user
      SPRING_DATASOURCE_PASSWORD: kairos-password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: A29qcCfi140LJPjCqzJHwlw8CmTJtrnjSwMYcp_e2Dk
    networks:
      - kairos

volumes:
  postgres_data:

networks:
  kairos:
