spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kairos-auth
    username: kairos-user
    password: kairos-password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

server:
  port: 8080

jwt:
  secret: A29qcCfi140LJPjCqzJHwlw8CmTJtrnjSwMYcp_e2Dk
  access-token-expiration: 900000       # 15 минут в мс
  refresh-token-expiration: 604800000   # 7 дней в мс