spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kairos-auth
    username: kairos-user
    password: kairos-password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: never

server:
  port: 8080