spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: kairos-user
    password: kairos-password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

server:
  port: 8080

jwt:
  secret: 22h9zhSFP/BzoNumS7obh0a3IWtcdifp+7XYcQVRkho=
  access-token-expiration: 900000 # 15 минут в мс
  refresh-token-expiration: 604800000 # 7 дней в мс
